export const fieldReviewed='September 6, 2026';
export type FieldQuestion={id:string;concept:string;module:number;prompt:string;options:string[];correct:number;feedback:string[];sources:string[]};
export const concepts=[
 {id:'payout',name:'Allotment versus personal payment',module:6},
 {id:'campus',name:'The campus compensation share',module:6},
 {id:'growth',name:'Growth versus test performance',module:3},
 {id:'components',name:'Required performance evidence',module:3},
 {id:'standards',name:'Benchmarks versus designation decisions',module:4},
 {id:'submission',name:'Proposed versus approved designations',module:8},
];
const make=(concept:string,module:number,rows:[string,string[],number,string[]][],sources:string[]):FieldQuestion[]=>rows.map(([prompt,options,correct,feedback],i)=>({id:`${concept}-${i}`,concept,module,prompt,options,correct,feedback,sources}));
export const fieldQuestions:FieldQuestion[]=[
 ...make('payout',6,[
 ['Elena and Sam have the same designation at different campuses. What should they check before comparing payments?',['Their campus allotments and district spending plans','Only their designation labels','Only who completed training first'],0,['You’ve got it. Local distribution and campus funding matter.','A shared label does not establish the same payment. Check funding and the local plan.','Training order does not set the payment. Use the applicable funding and spending plan.']],
 ['A teacher sees a campus allotment online. Which question belongs in a conversation with payroll?',['When will TEA send that amount directly to me?','How does our plan turn this allotment into my compensation?','Can I assume this is my take-home amount?'],1,['The allotment goes to the district. Ask how its plan distributes compensation.','Right. Ask about distribution, payment structure and applicable deductions.','An allotment is not a take-home quote. Ask payroll about the plan and deductions.']],
 ['Two districts use different payment methods. One uses salary increases and another uses stipends. What is the useful next step?',['Assume only stipends are allowed','Assume both teachers take home the entire allotment','Read each spending plan and its payment terms'],2,['Spending guidance allows both approaches. Read the plans.','Neither payment method guarantees the full allotment as take-home pay.','Right. Spending plans explain how compensation is distributed.']],
 ],['spending']),
 ...make('campus',6,[
 ['In a fictional example, an allotment is $20,000. What does the 90% rule require?',['$18,000 directly to one teacher after deductions','At least $18,000 for eligible teacher compensation at the campus','Exactly $2,000 for the designated teacher'],1,['$20,000 × 0.90 = $18,000, but the rule concerns campus compensation, not one net payment.','Right. $20,000 × 0.90 = $18,000 for eligible campus teacher compensation.','The minimum campus share is $18,000, not $2,000.']],
 ['A teacher asks whether the 90% share must all go to the designated teacher. Which answer fits the rule?',['Yes, as a personal net payment','No, the campus compensation requirement and the individual distribution are different','No, it can all fund unrelated central-office expenses'],1,['The requirement applies to eligible campus compensation. The plan determines individual distribution.','Right. Consult the plan for how that campus share is distributed.','The campus share is restricted to eligible campus teacher compensation.']],
 ['A hypothetical $8,000 allotment is being planned. What is its minimum campus compensation share?',['$800','$8,000 to one teacher','$7,200'],2,['$800 is 10%. The minimum campus share is $8,000 × 0.90 = $7,200.','The campus minimum is $7,200; the rule does not promise an individual payment.','Right. $8,000 × 0.90 = $7,200.']],
 ],['spending']),
 ...make('growth',3,[
 ['In a fictional class, 15 of 25 eligible students meet their growth targets. How should Maya describe the result?',['The average test score was 60%','60% of eligible students met their growth targets','Every student improved by 60 points'],1,['15 ÷ 25 × 100 = 60% meeting growth. It is not the average test score.','Right. 15 ÷ 25 × 100 = 60% meeting growth.','This result counts students meeting targets; it does not measure a 60-point gain.']],
 ['A report says 80% of students reached proficiency. Can that alone tell a teacher the percentage meeting growth?',['Yes, proficiency and growth are identical','Yes, use 80% as the growth result','No, examine results against the applicable growth targets'],2,['Proficiency and progress against growth targets answer different questions.','Do not relabel proficiency as growth. Check the district measure.','Right. The growth result requires the applicable growth evidence.']],
 ['In a fictional group, 9 of 12 eligible students meet growth. Which interpretation is accurate?',['75% met growth targets','Students averaged 75% correct','Three students automatically qualify for a designation'],0,['Right. 9 ÷ 12 × 100 = 75% meeting growth.','75% describes the share meeting growth, not their average test percentage.','The calculation describes student growth results, not teacher designations.']],
 ],['levels','guide']),
 ...make('components',3,[
 ['Maya asks whether a strong observation (for example, T-TESS) can replace student growth evidence. What should Riley explain?',['Yes, a strong observation (for example, T-TESS) is enough','Only if the teacher requests it','The local system requires both observation (for example, T-TESS) and student growth'],2,['A strong observation (for example, T-TESS) does not remove the growth component.','Teacher preference does not remove required system components.','Right. Both components belong in the local system.']],
 ['A team has growth results but no observation evidence (for example, T-TESS). What is missing from its proposed approach?',['Nothing, growth replaces observation (for example, T-TESS)','The required observation component (for example, T-TESS)','A promise of maximum compensation'],1,['Growth does not replace the observation component (for example, T-TESS).','Right. Both observation (for example, T-TESS) and growth are required components.','Compensation promises do not supply missing performance evidence.']],
 ['Which evidence pair belongs in a local designation system?',['Teacher observation (for example, T-TESS) and student growth','Attendance at training and app points','Only the most favorable test score'],0,['Right. The system includes observation (for example, T-TESS) and growth evidence.','Participation and app points do not replace required performance components.','One test score does not supply both required components.']],
 ],['levels']),
 ...make('standards',4,[
 ['Jordan meets one statewide observation benchmark (for example, T-TESS). What should happen next?',['Announce a final designation','Check the full local criteria, growth evidence and eligibility','Skip the district criteria'],1,['One benchmark does not establish the final decision.','Right. A benchmark is part of the context, not a standalone guarantee.','The district criteria still matter.']],
 ['A colleague uses a statewide reference percentage as a cap on local designations. What is the issue?',['A reference percentage is not a district quota','It is always a cap','It guarantees that exact number of designations'],0,['Right. Do not convert a statewide reference into a local cap or guarantee.','The reference does not impose that fixed cap.','A reference percentage cannot guarantee a district result.']],
 ['A teacher asks an app to award a designation from one score. What should the app do?',['Award it if the score looks high','Copy a colleague’s result','Explain that local criteria and the official process determine the result'],2,['A high score alone does not authorize a designation.','A colleague’s result does not establish this teacher’s result.','Right. Use the full criteria and official process.']],
 ],['levels']),
 ...make('submission',8,[
 ['Luis sees a successful file upload. What should he call the designations in an update?',['Final awards','Proposed designations pending the remaining process','Guaranteed payments'],1,['Upload success does not establish final approval.','Right. Validation, review and eligibility requirements remain.','Uploading does not guarantee compensation.']],
 ['A colleague says Texas Tech validation and TEA review are the same step. How should Luis respond?',['They have distinct responsibilities in the process','The app replaces both','Neither step matters after upload'],0,['Right. Texas Tech validates data; TEA reviews the system and verifies eligibility.','A learning app does not replace official review.','Upload is not the end of the process.']],
 ['A team wants to announce final awards because every spreadsheet cell is filled. What is the best response?',['A full spreadsheet guarantees approval','Only its formatting matters','Completion of the file does not establish validation or final approval'],2,['Filled cells do not establish validity or approval.','Formatting alone does not resolve validation and eligibility.','Right. Communicate proposed results accurately while the process continues.']],
 ],['validation']),
];
export const fieldCases=[
 {id:'river-pay',title:'Two teachers, two payments',module:6,intro:'Fictional case: At the River Walk, Elena asks Riley why her payment might differ from Sam’s. Help her sort out district funding and personal compensation.',questions:['payout-0','campus-0'],takeaway:'Ask your district how its spending plan distributes the campus allotment and affects your payment.'},
 {id:'school-growth',title:'What does 60% really mean?',module:3,intro:'Fictional case: Maya brings a growth report to the schoolhouse. Help her interpret the number and identify the evidence her local system needs.',questions:['growth-0','components-0'],takeaway:'Check which growth measure applies to your assignment, then connect growth and observation evidence (for example, T-TESS).'},
 {id:'mission-upload',title:'Uploaded. Ready to announce?',module:8,intro:'Fictional case: Luis has uploaded a file and is drafting an update at mission control. Help him explain the remaining process accurately.',questions:['submission-0','submission-1'],takeaway:'Use proposed or pending language until the official process establishes the outcome.'},
];
export const legacyConcepts:Record<string,string>={'0:0':'payout','0:1':'payout','3:0':'growth','3:1':'components','4:0':'standards','4:1':'standards','6:0':'campus','6:1':'payout','7:0':'payout','7:1':'payout','8:0':'submission','8:1':'submission'};
